### ISSUE TITLE
Explore modal.com

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#113]
How can we take advantage of modal.com? They've given us free API credits for the Tribe AI LLM hackathon.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/774615/236704684-aad25198-bc96-4b48-8a74-cf52a4a876ea.png">

**Comment by FFFiend** [comment]
We can certainly make Transformers/LLM's available for Mac users as addressed in the PR above, I believe they have certain NVIDIA (CUDA Enabled obviously) GPU's that they offer with documentation [here.](https://modal.com/docs/reference/modal.gpu)

**Comment by angelala3252** [comment]
As outlined at https://modal.com/docs/guide, starting up should be pretty quick, we just need to:

- Create an account at [modal.com](https://modal.com/)
- Install the ```modal-client``` package
- Set up a token

Modal would be helpful because:

- as FFFiend mentioned above, this would allow users with computers that would normally not be able to run certain features to fully run everything OpenAdapt needs
- it provides lightweight container environments which save a lot of time spent in downloading requirements and preparing all the dependencies, etc.
- would be very helpful in the future when we would need to scale up and accommodate more users
