### ISSUE TITLE
One-click download and install

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#123]
The website says:

> No programming required.

But we are scaring users off with:

> [Download and install Git](https://git-scm.com/download/)
> [Download and install Python](https://www.python.org/downloads/)
...
> Copy and paste the following command into the terminal, and press Enter:

This task involves reducing the onboarding to a single installer.

https://pyinstaller.org/en/stable/ will come in handy.

@apgorton the previous repo has (or had) instructions for building on Windows with pyinstaller.

**Comment by 0dm** [comment]
@abrichr 
I think we should first create a GUI for OpenAdapt with buttons like 
- "Record"
- "Visualize"
- "Playback" - Can incorporate the different strategies via another window, or keep it simple with NaiveReplay for now
- "Clear cache"

Not only with this scare less users away (and possibly attract more), but creating the installer will be a lot easier since we'd have a main file.py to feed into pyinstaller. Currently, users are required to choose which module they want to run via CLI, but it'd be a lot easier for them if they all ran the same file and chose a module from there. I can create an issue for this if you'd like.

**Comment by abrichr** [comment]
Related: https://github.com/MLDSAI/OpenAdapt/issues/149

**Comment by abrichr** [comment]
Addressed in https://github.com/MLDSAI/OpenAdapt/pull/135

**Comment by abrichr** [comment]
Related: https://github.com/OpenAdaptAI/OpenAdapt/issues/100
