### ISSUE TITLE
Implement AI-Hero Integration

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt#58]
How can we take advantage of https://github.com/ai-hero/llm-tools ?

**Comment by Mustaballer** [comment]
Some ways we can use the llm tools(now moment-tools) is:
- **Structured representation of context**: Using Moment Definition Language (MDL), the program can use this structured representation, the LLM model can better understand the context of the input and generate more accurate and relevant completions.
- Increased flexibility and adaptability: Moments allows for the representation of a wide range of contexts, including the agent's own thoughts, actions, and instructions. This makes the system more flexible and adaptable, as it can be customized to work with different types of inputs and contexts. The enhanced flexibility can be useful to us since we do deal with various formats of InputEvents.

Some downsides there isn't much documentation currently on how to use the tools, and its still very much in development. So some features have been proposed but not yet implemented.
