### ISSUE TITLE
please make docker type installation for ease.

### ISSUE THREAD

**Issue by hemangjoshi37a** [OpenAdaptAI/OpenAdapt#629]
### Feature request

please make docker type installation for ease.

### Motivation

please make docker type installation for ease.

**Comment by abrichr** [comment]
Hi @hemangjoshi37a , thanks for submitting this issue!

Unfortunately because Docker images run inside the Docker virtual machine, and OpenAdapt needs to access the host machine's mouse, keyboard, and monitor, it isn't possible for OpenAdapt to run inside of Docker.

However, we are working on simplifying the installation process here: https://github.com/OpenAdaptAI/OpenAdapt/pull/618
